wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/train_wind.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1663286743.183948
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.13.3
      8:
      - 3
      - 5
base_filter:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 64
c_out:
  desc: null
  value: 1
checkpoints:
  desc: null
  value: exp/wind_checkpoints/
cols:
  desc: null
  value: null
concat_len:
  desc: null
  value: 0
data:
  desc: null
  value: Wind_speed_data
data_path:
  desc: null
  value: Wind_speed_data.csv
dec_in:
  desc: null
  value: 1
detail_freq:
  desc: null
  value: h
devices:
  desc: null
  value: '0'
embed:
  desc: null
  value: timeF
enc_in:
  desc: null
  value: 1
evaluate:
  desc: null
  value: false
features:
  desc: null
  value: S
freq:
  desc: null
  value: h
gpu:
  desc: null
  value: 0
groups:
  desc: null
  value: 1
input_channel:
  desc: null
  value: 32
inverse:
  desc: null
  value: false
itr:
  desc: null
  value: 0
kernel:
  desc: null
  value: 3
label_len:
  desc: null
  value: 32
lastWeight:
  desc: null
  value: 1.0
loss:
  desc: null
  value: RMSE
lr:
  desc: null
  value: 0.0001
lradj:
  desc: null
  value: 1
model:
  desc: null
  value: ResNet1D
model_name:
  desc: null
  value: ResNet1D
n_block:
  desc: null
  value: 4
n_classes:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 0
patience:
  desc: null
  value: 10
pred_len:
  desc: null
  value: 64
resume:
  desc: null
  value: false
root_path:
  desc: null
  value: ./dataset/
save:
  desc: null
  value: false
seq_len:
  desc: null
  value: 32
single_step:
  desc: null
  value: 0
single_step_output_One:
  desc: null
  value: 0
stride:
  desc: null
  value: 2
target:
  desc: null
  value: 60m
train_epochs:
  desc: null
  value: 100
use_amp:
  desc: null
  value: false
use_gpu:
  desc: null
  value: false
use_multi_gpu:
  desc: null
  value: false
